### ISSUE TITLE
IE8 document.getElementById(hash)

### ISSUE THREAD

**Issue by ghost** [drublic/css-modal#119]
Hello!
please tell me I can not understand why does not work plugin in the IE8 with 1.4 and v1.1.0beta1
http://joxi.ru/XrN-U_3JTJDEMIoSx0Y

On this site 
http://sianie1.ru/

click this button
http://joxi.ru/q7R-UxjKTJAkTpilPAY

**Comment by Tuning-Soft** [comment]
@drublic , hello!
Now i'm update css-modal to 1.3.0 version and it's still not working for me in IE8
![2015-03-22_01 57 48](https://cloud.githubusercontent.com/assets/1108013/6766616/185b75b0-d037-11e4-9db2-7924577edfd5.png)

**Comment by Tuning-Soft** [comment]
error appears after about a minute, the browser hangs

**Comment by drublic** [comment]
There is another bug about this behavior here: #186
Please check again with the current master version.
