### ISSUE TITLE
Scrolling on iOS

### ISSUE THREAD

**Issue by dhunink** [drublic/css-modal#153]
Hi There!

I was struggling with a modal of my own, were the div.modal-content has more content then what fit's into in iPad screen. I noticed that when scrolling it was the background that scrolled and not, as one would expect, the content inside the div.modal-content. So I started debugging...

I noticed that the problem actually is also present in the Photo Gallery demo on http://drublic.github.io/css-modal/#modal-pictures . Little screenshot below: the content of the modal doesn't fit (that's not a big deal) but is also not scrollable. The background is crolling instead.

Tested on iOS 7 (latest release) and iOS 8 (latest Beta).

Although I saw some commits that were intended to deal with this or a similar problem, the issue is present. Any thoughts on the problem would be highly valued!

![img_0172](https://cloud.githubusercontent.com/assets/2500356/4100122/e51da36c-3081-11e4-8684-08279eec53b9.PNG)

**Comment by drublic** [comment]
Thanks for the report and sorry for handling this issue this late.
The latest master has some commits that might fix this issue. My tests with the visual test (`index.html`) indicate this although the background still scrolls if touch outside the modal.

Please let me know of your test results.

**Comment by drublic** [comment]
Please also see 3c66b9f027520e37fe78d6ae90e9eb190e18ec13. This should fix this issue mostly.
