### ISSUE TITLE
Not working in IE8 and IE9+

### ISSUE THREAD

**Issue by Komald** [drublic/css-modal#169]
Hello There,

I am facing a situation for IE browser all versions. I am having a link to open a modal and another link on that modal to close current modal and open another one. This works perfectly well in rest of the leading browsers, but fails in IE. The processes executes well till opening first modal, but when I click link to open another modal, the first one closes (as expected) but does not opens the second.

Here is the fiddle link 
http://jsfiddle.net/seyfso6L/

Hope this will help to understand the issue. Please have a look.

Thanks,
-Komal

**Comment by drublic** [comment]
So I've checked this again.

Currently the second modal opens "stacked" above the first one. This happens in IE9 and Chrome for me.
If you don't want this behavior, but want to open the first, then click, (close the first), open the second, close the second and be back at the page without any modal you might want to add `data-stackable="false"` to the second modal's `section` element.

Stackable modals don't seem to work in IE8 and 9 according to my tests.

**Comment by drublic** [comment]
Stackable modals should be fixed now.

**Comment by drublic** [comment]
Closing this now. Please let me know if you have any problems with it.
