### ISSUE TITLE
Page scrolls on modal open

### ISSUE THREAD

**Issue by smnk** [drublic/css-modal#174]
On Safari and Chrome, I notice some weird page jumping/scrolling when clicking on a modal button. Notice the buttons keep going lower on screen and eventually fall out of the window in the screencapture below. This also happens on mobile (iPhone). It's pretty disruptive for the user experience.

![cssmodaljumpy](https://cloud.githubusercontent.com/assets/3998912/5595816/18da26b4-927d-11e4-8c30-6a79f656ee37.gif)

**Comment by drublic** [comment]
Thanks for reporting this. Can you please check back with the latest commit in master? It should fix a couple of these issues. I could not reproduce this issue with the visual test in `index.html`.

**Comment by smnk** [comment]
Can't reproduce it with the latest commit. Thanks!

**Comment by drublic** [comment]
Awesome. Thank you!
