### ISSUE TITLE
Form inside of modal

### ISSUE THREAD

**Issue by CalebEverett** [drublic/css-modal#180]
Thank for the very nice modal. Sorry for the noob quetions. I have a form inside of the modal with a submit button. How can I close the modal when the submit button is clicked.

Also, how can I remove the close bar and button on the small screen. Users can close the modal with the back button on mobile devices and I want them to otherwise close the modal by submitting a form.

Thank you,

**Comment by drublic** [comment]
> Thank for the very nice modal. Sorry for the noob quetions. I have a form inside of the modal with a submit button. How can I close the modal when the submit button is clicked.

Please just change the hash on submission. With jQuery this looks like this:

    $('form').on('submit', function () {
        window.location.href = '#!';
    });

> Also, how can I remove the close bar and button on the small screen.

You need to dig a bit deeper into the styles might take some time to do so.
