### ISSUE TITLE
hashchange event not firing

### ISSUE THREAD

**Issue by jgadbois** [drublic/css-modal#182]
The `hashchange` event isn't firing for me in the modal css which in turn causes the `cssmodal:` events to fail.  Currently working around by using the `data-cssmodal-nohash` property, but ideally I would like to remove that.

**Comment by jgadbois** [comment]
Any ideas on this one?

**Comment by chilblane** [comment]
Are you using any iframes, such as to youtube? Having an issue where modal.js is trying to listen for hashchange within the youtube iframe and breaking as a result.

**Comment by drublic** [comment]
@jgadbois Thanks for reporting. I could not find any bugs with the `hashchange` event. As @chilblane points out this might be some other script blocking the `hashchange` event.

**Comment by jgadbois** [comment]
I believe I was using youtube iframe embeds.

**Comment by drublic** [comment]
Thank you for the quick feedback. I will close this issue. If you run into this behavior again, please let me know :)
