### ISSUE TITLE
Video does not stop when modal is close

### ISSUE THREAD

**Issue by droidsignage** [drublic/css-modal#185]
Both HTML5 and Youtube video keep playing after the modal has been closed.  How would I link the close function to stopping both video types?

**Comment by drublic** [comment]
Hi, thanks for the heads up and thanks for using CSS Modal.

We've build two plugins for that. Please see the plugins folder and search
the issues. We've already answered this, I think. I hope it helps :)

Please let us know if you need anything else.

**Comment by tmpkco** [comment]
Hans,

I've contacted you about some issues previously, and this was one of them. Including the plugins that you mention above did not solve the issue on the site I was developing. Unfortunately, I cannot provide the code. I had it configured as shown, an even referenced your examples, but I had the same issue.

**Comment by drublic** [comment]
@tmpkco Please check out master and test index.html: css-modal/#modal-html5video. Does the video stop function for you? You can always post a reduced example. That is what I'd be happy to work with :)

**Comment by rafagaseo** [comment]
I solved adding **onclick="pauseVid()"** in the element that have the class `.modal-close` 

And I Added in js
```javascript
var vid = document.getElementById("video");
function pauseVid() {
    video.pause();
}

**Comment by drublic** [comment]
Closing this as there was no more information provided. Please let me know if the bug persists.
