### ISSUE TITLE
Modal doesn't work in IE8

### ISSUE THREAD

**Issue by tmpkco** [drublic/css-modal#186]
Although it is listed as "functional" in IE8, I did not find this to be the case. The modal would not fire as expected.

**Comment by mendelk** [comment]
+1

**Comment by drublic** [comment]
Have you checked this with the version on master? I have now pushed a fix for the index file. This fixes it for me.
Can you please have another look at the issue?

**Comment by drublic** [comment]
Will not be handled, IE8 support will be removed.
