### ISSUE TITLE
Modal scrolling to top 

### ISSUE THREAD

**Issue by jimzar** [drublic/css-modal#187]
If I set the following heights
```
html, body {
  height: 100%;
}
```
when I click to open the modal, window scrolls to top.

Is there any way to avoid this ?

**Comment by josh1324** [comment]
I had the same problem, I removed this in modal-core.scss to fix the problem.
```
 .has-overlay {
	overflow: hidden;
	> body {
		height: 100%;
		overflow: hidden;
	}
 }
```

**Comment by drublic** [comment]
Thanks for the report. I've now worked around this by setting a default height of `auto` when setting `.has-layout` to `html`. This should fix it. If you have any other issue with this implementation, please let me know :)
