### ISSUE TITLE
Programatically dismiss the modal

### ISSUE THREAD

**Issue by mokargas** [drublic/css-modal#189]
How would I dismiss this modal from a JS function? I've tried simulating clicks on the close button and removing the is-active class to no avail.

**Comment by VersatilityWerks** [comment]
Try jAlert http://flwebsites.biz/jAlert/ and use $('.jAlert').closeAlert();

**Comment by drublic** [comment]
Just push a new hash to the location object:

    location.hash = '';

Also see: https://github.com/drublic/css-modal/blob/master/FAQ.md#is-it-possible-to-show-modal-on-page-load You cant to do the reverse thing.
