### ISSUE TITLE
Strange scrolling bug

### ISSUE THREAD

**Issue by bojidar-bg** [drublic/css-modal#191]
#### Problem:
After opening a modal, the window scrolls a bit up. Also the "close" button is cut in the middle.
#### Steps to reproduce:
1. Open http://drublic.github.io/css-modal/
2. Scroll down to "Examples"
3. Open the "Text" example.
4. See the problem

P.S. I'm not really sure if this is a bug...

**Comment by drublic** [comment]
Thanks for reporting. Is this still a bug? I think this was something we had in earlier versions.
I currently cannot reproduce this problem with my Chrome on Mac.

**Comment by bojidar-bg** [comment]
Seems like it's gone...
