### ISSUE TITLE
Incorrect function calls - modal.js

### ISSUE THREAD

**Issue by sunnybear** [drublic/css-modal#198]
Here are at least two incorrect function calls:
modal.setFocus(element.id);
there should be 0 arguments

modal.unsetActive();
there should 2 arguments

Please check JS code with any JS validator (at least with https://closure-compiler.appspot.com/ )

**Comment by drublic** [comment]
Thank you. This is fixed in 6e3c773647e85cd57f8343337236a20dbf93328c.
Will not be present in the new version.
