### ISSUE TITLE
cssmodal:show / cssmodal:hide dialog reference in event

### ISSUE THREAD

**Issue by blocknotes** [drublic/css-modal#217]
It would be nice to have a dialog element reference (or just the id) of the current dialog in _event_
For _cssmodal:show_ I'm using _window.location.hash_
But for _cssmodal:hide_ ... ?

**Comment by drublic** [comment]
Hello @blocknotes, this makes sense. Care about creating a PR against master?

**Comment by blocknotes** [comment]
Hi @drublic 
I made some tests and discovered that I can get the id from the second argument.
If `element.detail.modal.id` is always reliable it should be ok.
I close the issue.

```
$(document).on('cssmodal:show', function( event, element ) {
  var id = element.detail.modal.id;
  console.log( 'cssmodal:show', id );
});

$(document).on('cssmodal:hide', function( event, element ) {
  var id = element.detail.modal.id;
  console.log( 'cssmodal:hide', id );
});
```
