### ISSUE TITLE
Get rid of hashbang

### ISSUE THREAD

**Issue by cyxou** [drublic/css-modal#99]
Hi! First I'd like to thank you for your work, css-modal is really cool)) 

I use it in my firefox extension. When a user launches it, it injects in the currently opened webpage the  css-modal section with an iframe that displays my site. My extension is supposed to work with any site. But I've noticed that on some sites when the css-modal is opened via the hashbang, the website is redirected to a 404 page. This is because of the hashbang appended to the url of the page...
Is there a way to popup a modal without using the hashbang stuff or to prevent a website from redirection?

**Comment by drublic** [comment]
Done. Will be included within the next version.
